"DOTAHeroes"
{
    //=================================================================================================================
    // Malganis
    //=================================================================================================================
	"npc_dota_hero_malganis"
	{
		"override_hero"				"npc_dota_hero_night_stalker"			// Hero to override
		"Ability1"					"malganis_fel_claws"		// Ability 1
		"Ability3"					"malganis_night_rush"		// Ability 1
	}
}