"DOTAHeroes"
{
	//=================================================================================================================
    // Nazeebo
    //=================================================================================================================
	"npc_dota_hero_nazeebo"
	{
		"override_hero"				"npc_dota_hero_witch_doctor"			// Hero to override
		"Ability1"					"nazeebo_corpse_spiders"		// Ability 1
	}
}